name: Build on Pr

on: 
  pull_request:
    branches: 
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20'
      - name: installing dependencies 
        run: npm install
      - name: runing build 
        run: npm run build
